### PR TITLE
docs: update changelog

### PR DESCRIPTION
**Pull request by zulfiqarjunejo**

### CODE REVIEW

**Comment by ghost** [comment]
@zulfiqarjunejo 

I would do in reverse order, as the other changelogs ... like this one here: https://github.com/egomobile/node-http-server/blob/master/CHANGELOG.md

**Comment by zulfiqarjunejo** [comment]
> @zulfiqarjunejo
> 
> I would do in reverse order, as the other changelogs ... like this one here: https://github.com/egomobile/node-http-server/blob/master/CHANGELOG.md

Understood :)

**Comment by ghost** [comment]
@zulfiqarjunejo 

oh, i forgot: please bump the `patch` version of the package, otherwise it is not published to npm

**Comment by zulfiqarjunejo** [comment]
@mkloubertego ready for merge?

**Comment by ghost** [comment]
@zulfiqarjunejo 

lot of conversation for a small change :D

**Pull request merged**
